FROM rust:1.59 as builder
WORKDIR /build
COPY . .
RUN cargo build --bin anime --release

FROM photon:latest
EXPOSE 8080
COPY --from=builder /build/target/release/anime /usr/local/bin/anime
CMD ["anime"]